COUNTRIES = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "DZA": "Algeria",
    "AGO": "Angola",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AZE": "Azerbaijan",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BRA": "Brazil",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CPV": "Cape Verde",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo",
    "CRI": "Costa Rica",
    "CIV": "Côte d'Ivoire",
    "CUB": "Cuba",
    "COD": "Democratic Republic of the Congo",
    "DJI": "Djibouti",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "ETH": "Ethiopia",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "GHA": "Ghana",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "KGZ": "Kyrgyzstan",
    "LAO": "Lao People's Democratic Republic",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MRT": "Mauritania",
    "MEX": "Mexico",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar",
    "NAM": "Namibia",
    "NPL": "Nepal",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "PSE": "Occupied Palestinian Territory",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "QAT": "Qatar",
    "RWA": "Rwanda",
    "LCA": "Saint Lucia",
    "WSM": "Samoa",
    "STP": "São Tomé and Príncipe",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SLE": "Sierra Leone",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWZ": "Swaziland",
    "SYR": "Syrian Arab Republic",
    "TJK": "Tajikistan",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TKM": "Turkmenistan",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "TZA": "United Republic of Tanzania",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VNM": "Viet Nam",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
    "004": "Afghanistan",
    "008": "Albania",
    "012": "Algeria",
    "024": "Angola",
    "032": "Argentina",
    "051": "Armenia",
    "031": "Azerbaijan",
    "050": "Bangladesh",
    "052": "Barbados",
    "112": "Belarus",
    "084": "Belize",
    "204": "Benin",
    "064": "Bhutan",
    "068": "Bolivia",
    "070": "Bosnia and Herzegovina",
    "072": "Botswana",
    "076": "Brazil",
    "854": "Burkina Faso",
    "108": "Burundi",
    "116": "Cambodia",
    "120": "Cameroon",
    "132": "Cape Verde",
    "140": "Central African Republic",
    "148": "Chad",
    "170": "Colombia",
    "174": "Comoros",
    "178": "Congo",
    "188": "Costa Rica",
    "384": "Côte d'Ivoire",
    "192": "Cuba",
    "180": "Democratic Republic of the Congo",
    "262": "Djibouti",
    "214": "Dominican Republic",
    "218": "Ecuador",
    "818": "Egypt",
    "222": "El Salvador",
    "226": "Equatorial Guinea",
    "232": "Eritrea",
    "231": "Ethiopia",
    "266": "Gabon",
    "270": "Gambia",
    "268": "Georgia",
    "288": "Ghana",
    "320": "Guatemala",
    "324": "Guinea",
    "624": "Guinea-Bissau",
    "328": "Guyana",
    "332": "Haiti",
    "340": "Honduras",
    "356": "India",
    "360": "Indonesia",
    "368": "Iraq",
    "388": "Jamaica",
    "400": "Jordan",
    "398": "Kazakhstan",
    "404": "Kenya",
    "296": "Kiribati",
    "417": "Kyrgyzstan",
    "418": "Lao People's Democratic Republic",
    "426": "Lesotho",
    "430": "Liberia",
    "450": "Madagascar",
    "454": "Malawi",
    "462": "Maldives",
    "466": "Mali",
    "478": "Mauritania",
    "484": "Mexico",
    "496": "Mongolia",
    "499": "Montenegro",
    "504": "Morocco",
    "508": "Mozambique",
    "104": "Myanmar",
    "516": "Namibia",
    "524": "Nepal",
    "558": "Nicaragua",
    "562": "Niger",
    "566": "Nigeria",
    "275": "Occupied Palestinian Territory",
    "586": "Pakistan",
    "591": "Panama",
    "598": "Papua New Guinea",
    "600": "Paraguay",
    "604": "Peru",
    "608": "Philippines",
    "634": "Qatar",
    "646": "Rwanda",
    "662": "Saint Lucia",
    "882": "Samoa",
    "678": "São Tomé and Príncipe",
    "686": "Senegal",
    "688": "Serbia",
    "694": "Sierra Leone",
    "090": "Solomon Islands",
    "706": "Somalia",
    "710": "South Africa",
    "728": "South Sudan",
    "144": "Sri Lanka",
    "729": "Sudan",
    "740": "Suriname",
    "748": "Swaziland",
    "760": "Syrian Arab Republic",
    "762": "Tajikistan",
    "764": "Thailand",
    "626": "Timor-Leste",
    "768": "Togo",
    "776": "Tonga",
    "780": "Trinidad and Tobago",
    "788": "Tunisia",
    "792": "Turkey",
    "795": "Turkmenistan",
    "800": "Uganda",
    "804": "Ukraine",
    "834": "United Republic of Tanzania",
    "858": "Uruguay",
    "860": "Uzbekistan",
    "548": "Vanuatu",
    "704": "Viet Nam",
    "887": "Yemen",
    "894": "Zambia",
    "716": "Zimbabwe",
}


def get_country_name(code):
    return COUNTRIES[code.upper().rjust(3, "0")]
